<a href="https://colab.research.google.com/github/bosliu/IML-Outofboundary/blob/main/task0/task0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 0

In [2]:
import pandas as pd
import numpy as np

from typing import List, Union, Optional, Tuple

train: pd.DataFrame = pd.read_csv('train.csv')
# test: pd.DataFrame = pd.read_csv('test.csv')

In [3]:
train.head()

Id           y           x1           x2           x3           x4  \
0   0  738.023171  1764.052346   400.157208   978.737984  2240.893199   
1   1  400.646015   144.043571  1454.273507   761.037725   121.675016   
2   2  189.900156 -2552.989816   653.618595   864.436199  -742.165020   
3   3  -78.399449   154.947426   378.162520  -887.785748 -1980.796468   
4   4 -547.373531 -1048.552965 -1420.017937 -1706.270191  1950.775395   

            x5           x6           x7           x8           x9  \
0  1867.557990  -977.277880   950.088418  -151.357208  -103.218852   
1   443.863233   333.674327  1494.079073  -205.158264   313.067702   
2  2269.754624 -1454.365675    45.758517  -187.183850  1532.779214   
3  -347.912149   156.348969  1230.290681  1202.379849  -387.326817   
4  -509.652182  -438.074302 -1252.795360   777.490356 -1613.897848   

           x10  
0   410.598502  
1  -854.095739  
2  1469.358770  
3  -302.302751  
4  -212.740280

In [4]:
train_mat: np.ndarray = train.to_numpy()
train_y: np.ndarray = train_mat[:, 1]
train_x: np.ndarray = train_mat[:, 2:]

In [7]:
train_x_avg: np.ndarray = np.divide(train_x - np.min(train_x, axis=0), np.max(train_x, axis=0) - np.min(train_x, axis=0))
train_x_avg

array([[0.75534077, 0.55925853, 0.60810762, ..., 0.49663337, 0.5246668 ,
        0.54322957],
       [0.56485857, 0.69385042, 0.58005301, ..., 0.48919929, 0.57495253,
        0.37111521],
       [0.24773877, 0.59162104, 0.59337777, ..., 0.49168295, 0.72228876,
        0.68731803],
       ...,
       [0.48375727, 0.72481235, 0.41649059, ..., 0.65767886, 0.46676818,
        0.57428451],
       [0.50467702, 0.4355964 , 0.38903374, ..., 0.47523713, 0.4224931 ,
        0.4263701 ],
       [0.59831352, 0.48709813, 0.59344561, ..., 0.61788924, 0.39606601,
        0.31244447]])

In [9]:
train_y_avg: np.ndarray = np.divide(train_y - np.min(train_y), np.max(train_y) - np.min(train_y))
train_y_avg

array([0.81394836, 0.68589175, 0.60589997, ..., 0.55704097, 0.45709652,
       0.42404303])

In [10]:
# class Objective:
#     def __call__(self, w):
#         raise NotImplementedError()
#
#     def grad(self, w):
#         raise NotImplementedError()

class ObjFunc:
    def __init__(self, y: Union[np.ndarray, float], phi: np.ndarray):
        self.y = y.astype(np.float64)
        self.phi = phi.astype(np.float64)  # feature input
        self.n = self.y.shape[0]

    def __call__(self, w: np.ndarray) -> Union[float, np.ndarray]:
        return np.linalg.norm(self.y - self.phi @ w) ** 2 / self.n

    def grad(self, w: np.ndarray) -> np.ndarray:
        return 2 * self.phi.T @ (self.phi @ w - self.y) / self.n


class ObjFuncSDG(ObjFunc):
    def __init__(self, y: Union[np.ndarray, float], phi: np.ndarray):
        super().__init__(y, phi)

    def grad(self, w: np.ndarray, indices: np.ndarray) -> np.ndarray:
        return 2 * self.phi[indices, :].T @ (self.phi[indices, :] @ w - self.y[indices]) / indices.shape[0]

In [ ]:
def gradient_descent(obj_func: ObjFunc, w_init: np.ndarray, lr: float, tol: float, max_steps: int) -> Tuple[np.ndarray, List, List]:
    w_curr = w_init
    w_hist: List[np.ndarray] = [w_init]
    obj_hist: List[Union[float, np.ndarray]] = [obj_func(w_curr)]
    for step in range(max_steps):
        direction: np.ndarray = obj_func.grad(w_curr)
        w_next = w_curr - lr * direction
        if np.allclose(w_next, w_curr, tol):
            break
        w_curr = w_next
        w_hist.append(w_curr)
        obj_hist.append(obj_func(w_curr))
    return w_curr, w_hist, obj_hist

In [11]:
def sgd(obj_func: ObjFuncSDG, w_init: np.ndarray, lr: float, tol: float, n_epoch: int, batch_size: int) -> np.ndarray:
    w_curr = w_init
    for epoch in range(n_epoch):
        rand_idx: np.ndarray = np.array([x for x in range(obj_func.n)], dtype=int)
        np.random.shuffle(rand_idx)
        error = np.zeros_like(w_curr)
        for i in range(0, obj_func.n, batch_size):
            batch_idx: np.ndarray = rand_idx[i: i + batch_size]
            direction: np.ndarray = obj_func.grad(w_curr, batch_idx)
            #direction = direction / np.linalg.norm(direction)
            # w_next = error * 0.9 - lr * direction + w_curr
            # error = w_next - w_curr
           #  print(obj_func(w_curr))
            w_next = w_curr - lr * direction
            if np.allclose(w_next, w_curr, tol):
                return w_next
            w_curr = w_next
    return w_next

In [12]:
# hyperparams

learning_rate = 0.001
tol = 1e-6
n_steps = 10000

batch_size = 100
num_of_epochs = 5

In [14]:
phi = train_x_avg.astype(np.float64)
phi = np.insert(phi, 0, 1, axis=1)

In [15]:
w_init = np.random.random(11)

# fitting = ObjFunc(y=train_y, phi=phi)
fitting = ObjFuncSDG(y=train_y_avg, phi=phi)

# w_res, _, _ = gradient_descent(fitting, w_init, lr=learning_rate, tol=tol, max_steps=n_steps)
w_res = sgd(fitting, w_init, lr=learning_rate, tol=tol, n_epoch=num_of_epochs, batch_size=batch_size)

In [18]:
w = np.multiply(w_res, np.insert(np.max(train_x, axis=0) - np.min(train_x, axis=0), 0, 1))
w

array([-4.66182378e-01,  2.17901258e+03,  3.73993968e+03,  8.58488649e+02,
        5.09514762e+03, -6.08055049e+01, -1.53527251e+03,  1.45995392e+03,
        1.14967032e+03,  3.30059416e+03,  6.69528144e+02])

In [ ]:
# use scikit_learn to compare the results
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(phi, train_y)
reg.coef_

array([0. , 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])